version: "3.3"
services:
  flask:
    build: .
    command: gunicorn -w 1 -b 0.0.0.0:5000 app:app --reload
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=True
    ports:
      - "5000:5000"
    volumes:
      - ./:/root
